### ISSUE TITLE
How to hang a skin on the dryer.

### ISSUE THREAD

**Issue by Styluse** [Jods-Its/Jods-Camping-Tools#7]
I couldn't find a mention of how to hang it, I also tried to give it out using the console, but another problem arose, I can't remove the skin from the dryer.

**Comment by Jods-Its** [comment]
Latest update of Camping tools require ExamineActionsAPI and Modder's Gear Toolbox mods to work (and be sure to delete previous version). Tanning racks can be assembled and disassembled through actions menu. If you got the mod from TLD ModList, there should be listed all the dependencies. 

If you need further assistance, you can contact me through the TLD Modding discord ^^

**Comment by Styluse** [comment]
Thank you for telling me that another mod is needed, apparently I did not carefully read what is needed for the mod.

**Comment by Jods-Its** [comment]
Dw! this one is on me, haven't updated the README yet
